#ifndef PRJ_CONFIG_H_
#define PRJ_CONFIG_H_

#include "board_config.h"


////////////////////////////////////////////////////////////////////////////////
// get bd in resolution resolution.
#if	((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD720H)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_IN_RESOLUTION		(vres_720x480i60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_IN_RESOLUTION		(vres_720x576i50)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD960H)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_IN_RESOLUTION		(vres_960x480i60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_IN_RESOLUTION		(vres_960x576i50)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH720)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_IN_RESOLUTION		(vres_720x480p60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_IN_RESOLUTION		(vres_720x576p50)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH960)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_IN_RESOLUTION		(vres_960x480p60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_IN_RESOLUTION		(vres_960x576p50)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD720P)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_IN_RESOLUTION		(vres_1280x720p60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_IN_RESOLUTION		(vres_1280x720p50)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_IN_RESOLUTION		(vres_1280x720p30)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_IN_RESOLUTION		(vres_1280x720p25)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD960P)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_IN_RESOLUTION		(vres_1280x960p30)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_IN_RESOLUTION		(vres_1280x960p25)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1080P)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_IN_RESOLUTION		(vres_1920x1080p30)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_IN_RESOLUTION		(vres_1920x1080p25)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD800_480P)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_IN_RESOLUTION		(vres_800x480p60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_IN_RESOLUTION		(vres_800x480p50)
	#endif
#elif ((BD_VIN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1024_600P)
	#if ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_IN_RESOLUTION		(vres_1024x600p60)
	#elif ((BD_VIN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_IN_RESOLUTION		(vres_1024x600p50)
	#endif
#endif

#if	((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD720H)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_RO_OUT_RESOLUTION		(vres_720x480i60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_RO_OUT_RESOLUTION		(vres_720x576i50)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD960H)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_RO_OUT_RESOLUTION		(vres_960x480i60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_RO_OUT_RESOLUTION		(vres_960x576i50)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH720)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_RO_OUT_RESOLUTION		(vres_720x480p60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_RO_OUT_RESOLUTION		(vres_720x576p50)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH960)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_RO_OUT_RESOLUTION		(vres_960x480p60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_RO_OUT_RESOLUTION		(vres_960x576p50)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD720P)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x720p60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x720p50)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x720p30)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x720p25)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD960P)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x960p30)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_RO_OUT_RESOLUTION		(vres_1280x960p25)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1080P)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_RO_OUT_RESOLUTION		(vres_1920x1080p30)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_RO_OUT_RESOLUTION		(vres_1920x1080p25)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD800_480P)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_RO_OUT_RESOLUTION		(vres_800x480p60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_RO_OUT_RESOLUTION		(vres_800x480p50)
	#endif
#elif ((BD_RO_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1024_600P)
	#if ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_RO_OUT_RESOLUTION		(vres_1024x600p60)
	#elif ((BD_RO_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_RO_OUT_RESOLUTION		(vres_1024x600p50)
	#endif
#endif

#if	((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD720H)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_QUAD_OUT_RESOLUTION		(vres_720x480i60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_QUAD_OUT_RESOLUTION		(vres_720x576i50)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD960H)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_QUAD_OUT_RESOLUTION		(vres_960x480i60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_QUAD_OUT_RESOLUTION		(vres_960x576i50)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH720)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_QUAD_OUT_RESOLUTION		(vres_720x480p60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_QUAD_OUT_RESOLUTION		(vres_720x576p50)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH960)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_QUAD_OUT_RESOLUTION		(vres_960x480p60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_QUAD_OUT_RESOLUTION		(vres_960x576p50)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD720P)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x720p60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x720p50)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x720p30)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x720p25)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD960P)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x960p30)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1280x960p25)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1080P)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1920x1080p30)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1920x1080p25)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD800_480P)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_QUAD_OUT_RESOLUTION		(vres_800x480p60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_QUAD_OUT_RESOLUTION		(vres_800x480p50)
	#endif
#elif ((BD_QUAD_OUT_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1024_600P)
	#if ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1024x600p60)
	#elif ((BD_QUAD_OUT_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_QUAD_OUT_RESOLUTION		(vres_1024x600p50)
	#endif
#endif

#if ( (VIDEO_IN_TYPE != VIDEO_IN_TYPE_PARALLEL) && (VIDEO_IN_TYPE_PB_SUPPORT == 1) )
#if	((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD720H)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_PB_IN_RESOLUTION		(vres_720x480i60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_PB_IN_RESOLUTION		(vres_720x576i50)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SD960H)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_PB_IN_RESOLUTION		(vres_960x480i60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_PB_IN_RESOLUTION		(vres_960x576i50)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH720)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_PB_IN_RESOLUTION		(vres_720x480p60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_PB_IN_RESOLUTION		(vres_720x576p50)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_SDH960)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_PB_IN_RESOLUTION		(vres_960x480p60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_PB_IN_RESOLUTION		(vres_960x576p50)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD720P)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_PB_IN_RESOLUTION		(vres_1280x720p60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_PB_IN_RESOLUTION		(vres_1280x720p50)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_PB_IN_RESOLUTION		(vres_1280x720p30)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_PB_IN_RESOLUTION		(vres_1280x720p25)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD960P)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_PB_IN_RESOLUTION		(vres_1280x960p30)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_PB_IN_RESOLUTION		(vres_1280x960p25)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1080P)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_30)
		#define BD_PB_IN_RESOLUTION		(vres_1920x1080p30)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_25)
		#define BD_PB_IN_RESOLUTION		(vres_1920x1080p25)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD800_480P)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_PB_IN_RESOLUTION		(vres_800x480p60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_PB_IN_RESOLUTION		(vres_800x480p50)
	#endif
#elif ((BD_VID_PB_IN_FMT & VID_RESOL_MASKBIT) == VID_RESOL_HD1024_600P)
	#if ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_NTSC_60)
		#define BD_PB_IN_RESOLUTION		(vres_1024x600p60)
	#elif ((BD_VID_PB_IN_FMT & VID_FRAME_MASKBIT) == VID_FRAME_PAL_50)
		#define BD_PB_IN_RESOLUTION		(vres_1024x600p50)
	#endif
#endif

#endif //( (VIDEO_IN_TYPE != VIDEO_IN_TYPE_PARALLEL) && (VIDEO_IN_TYPE_PB_SUPPORT == 1) )
/////////////////////////////////////////////////////////////////////////////////

#define ALLOC_DRAM_RESERVED   //allocate dram reserved.

//# Use Dynamic Blending library. If not, comment. 
#define DB_LIB_USE

/********** Define PROJECT variable on your IDE Environment **********/
//==========================================
//	A.Project Option
//==========================================
#define PRJ_SCENARIO					0
    
#define PROJECT 		PRJ_SCENARIO
#if (PROJECT == PRJ_SCENARIO)
	#include "prj_config_scenario.h"
#else
	#error "PROJECT IS NOT SPECIFIED!"
#endif

#endif /* PRJ_CONFIG_H_ */
